### ISSUE TITLE
packages.qmd typos, etc.

### ISSUE THREAD

**Issue by esimms999-gsk** [mjfrigaard/shinyap#10]

**Comment by esimms999** [comment]
When rendering, I noticed a warning. This is due to Shiny.qmd vs shiny.qmd:

[ 5/32] packages.qmd
- The project is out-of-sync -- use `renv::status()` for details.

processing file: packages.qmd                                                                                                                                   
output file: packages.knit.md

WARNING: Unable to resolve link target: Shiny.qmd

I made the change.

**Comment by esimms999** [comment]
On the top of this page, and many other pages: "This section is still being developed--it's contents are subject to change." I think it should be "its". I made the change in packages.qmd.

**Comment by esimms999** [comment]
Minor typos.
